# Generated by Django 4.0.4 on 2022-05-04 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aviabilet', '0004_alter_aviabilet_planes_review_favorite'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='passenger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='aviabilet.passenger'),
            preserve_default=False,
        ),
    ]
