# Generated by Django 4.0.4 on 2022-05-04 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='passenger',
        ),
    ]
