# Generated by Django 4.0.4 on 2022-05-02 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviabilet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aviabilet',
            name='destination_pl',
        ),
        migrations.RemoveField(
            model_name='aviabilet',
            name='source',
        ),
    ]
