# Generated by Django 4.0.4 on 2022-05-02 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aviabilet', '0002_remove_aviabilet_destination_pl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='carrier',
            new_name='airlines',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='aviabilet',
        ),
        migrations.AddField(
            model_name='rating',
            name='airlines',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='aviabilet.airlines'),
            preserve_default=False,
        ),
    ]
